#!/bin/bash

# USAGE: 
# Install requirements with `pip install -U -r misc/googlefonts-qa/requirements.txt`
# 
# use `ln -s <absolute_path>` to symbolically link this script into build/venv/bin, then activate the venv
# have a google/fonts repo on your local machine
# 
# after  `make -j all_ttf`
# call this script from the root of your inter repo, with the absolute path your your google/fonts repo
# `move-check <your_username>/<path>/fonts`

set -e
source build/venv3/bin/activate

gFontsDir=$1

if [[ -z "$gFontsDir" || $gFontsDir = "--help" ]] ; then
    echo 'Add absolute path to your Google Fonts Git directory, like:'
    echo 'move-check /Users/username/type-repos/google-font-repos/fonts'
    exit 2
fi

interDir=$(pwd)

interGfontsDir=$interDir/misc/googlefonts-qa

# -------------------------------------------------------------------
# navigate to google/fonts repo, then inter branch ------------------

cd $gFontsDir
git checkout master
git checkout -B inter

# -------------------------------------------------------------------
# move fonts --------------------------------------------------------

mkdir -p ofl/inter
cd ofl/inter

cp $interDir/build/fonts/var/Inter.var.ttf            Inter-Regular.ttf
cp $interDir/build/fonts/var/Inter-italic.var.ttf     Inter-Italic.ttf

mkdir -p static
statics=$(ls $interDir/build/fonts/const-hinted/*.ttf)
for ttf in $statics
do
    cp $ttf static/$(basename $ttf)
done

# -------------------------------------------------------------------
# make or move basic metadata ---------------------------------------

# TODO: make/update metadata with gftools add-font
# TODO: remove handmade metadata and replace with generated version (to have accurate subsets)
# gftools add-font .

cp $interDir/LICENSE.txt OFL.txt

cp $interGfontsDir/gfonts-description.html DESCRIPTION.en_us.html

# -------------------------------------------------------------------
# run checks, saving to inter/misc/googlefonts-qa/checks ------------

set +e # otherwise, the script stops after the first fontbakery check output

mkdir -p $interGfontsDir/checks/static

# ttfs=$(ls -R */*.ttf && ls *.ttf) # use this to statics and VFs
ttfs=$(ls *.ttf) # use this to check only the VFs

for ttf in $ttfs
do
    fontbakery check-googlefonts $ttf --ghmarkdown $interGfontsDir/checks/${ttf/".ttf"/".checks.md"}
done
