#!/bin/bash

# This script copies the latest builds to the google fonts dir in order to run QA checks and prep for a PR
#
# USAGE: 
# Install requirements with `pip install -U -r misc/googlefonts-qa/requirements.txt`
# 
# use `ln -s <absolute_path>` to symbolically link this script into build/venv/bin, then activate the venv
# have a google/fonts repo on your local machine
# 
# after  `make -j all_ttf`
# call this script from the root of your inter repo, with the absolute path your your google/fonts repo
# `move-check <your_username>/<path>/fonts`

set -e
source build/venv3/bin/activate

gFontsDir=$1

if [[ -z "$gFontsDir" || $gFontsDir = "--help" ]] ; then
    echo 'Add absolute path to your Google Fonts Git directory, like:'
    echo 'move-check /Users/username/type-repos/google-font-repos/fonts'
    exit 2
fi

interDir=$(pwd)

interQADir=$interDir/misc/googlefonts-qa

interUprightVF=$interDir/build/fonts/var/Inter-upright.var.ttf
interItalicVF=$interDir/build/fonts/var/Inter-italic.var.ttf

# -------------------------------------------------------------------
# fix variable font metadata as needed ------------------------------
# note: this assumes variable fonts have no hinting -----------------

# TODO: test VFs with TTFautohint-VF vs no hinting

gftools fix-nonhinting $interUprightVF $interUprightVF
gftools fix-nonhinting $interItalicVF $interItalicVF

# TODO: decide if `--autofix` is really the best option, or if we should assert more control
gftools fix-gasp --autofix $interUprightVF
gftools fix-gasp --autofix $interItalicVF

# -------------------------------------------------------------------
# navigate to google/fonts repo, then inter branch ------------------

cd $gFontsDir
git checkout master
git checkout -B inter

# -------------------------------------------------------------------
# move fonts --------------------------------------------------------

mkdir -p ofl/inter

cp $interUprightVF    ofl/inter/Inter-Regular.ttf
cp $interItalicVF     ofl/inter/Inter-Italic.ttf

mkdir -p ofl/inter/static
statics=$(ls $interDir/build/fonts/const-hinted/*.ttf)
for ttf in $statics
do
    cp $ttf ofl/inter/static/$(basename $ttf)
done

# -------------------------------------------------------------------
# make or move basic metadata ---------------------------------------

gftools add-font ofl/inter

cp $interDir/LICENSE.txt ofl/inter/OFL.txt

cp $interQADir/gfonts-description.html ofl/inter/DESCRIPTION.en_us.html

# -------------------------------------------------------------------
# run checks, saving to inter/misc/googlefonts-qa/checks ------------

set +e # otherwise, the script stops after the first fontbakery check output

mkdir -p $interQADir/checks/static

cd ofl/inter

# ttfs=$(ls -R */*.ttf && ls *.ttf) # use this to statics and VFs
ttfs=$(ls *.ttf) # use this to check only the VFs
# ttfs=$(ls -R */*.ttf ) # use this to check only statics

for ttf in $ttfs
do
    fontbakery check-googlefonts $ttf --ghmarkdown $interQADir/checks/${ttf/".ttf"/".checks.md"}
done
